@extends('layouts.inner')

@section('content-inner')
    <h3 xmlns="http://www.w3.org/1999/html">About this Policy</h3>
    <p>Futbolin and its affiliates (referred to as “Futbolin”, “us”, “our” or "we") are dedicated to protecting the privacy rights of our users (referred to as "user(s)" or "you"). For this reason, we are committed to protecting your personal data and using it only as appropriate to provide you with the best possible experience with all Futbolin games, the website futbolin.com.ar, user support and all other channels for feedback and news (collectively referred to as "services").</p>
    <p>This Privacy Policy describes what and why we collect and use your personal data that either you provide or we collect when you use our services. Please note that your access and/or playing our games implies your acceptance of this Privacy Policy as well as our Terms of Service.</p>
    <p><strong>IF YOU DO NOT AGREE WITH THIS PRIVACY POLICY PLEASE DO NOT ACCESS AND/OR PLAY OUR GAMES OR USE OUR SERVICES.</strong></p>
    <h3>Key Terms</h3>
    <p><strong>Affiliates:</strong> People or companies outside Futbolin staff, whom we cooperate with closely and regularly, that have access to your personal data in order for us to provide our services.</p>
    <p><strong>Personal data:</strong> information that you provide to us or we collect which personally identifies you, such as your name, username, email address or geographic region.</p>
    <p><strong>Processing:</strong> includes collection, registration, organization, storage, processing or modification, reading, use, transmission of, dissemination or otherwise providing, adjustment or assembly, restriction, erasure or destruction of personal data.</p>
    <p><strong>Data controller/controller:</strong> The controller is usually the legal person (such as a company, foundation, authority or association) that processes personal data and determines the purpose of processing.</p>
    <p><strong>Data processor/processor:</strong> The processor is the person (or company) who processes personal data on behalf of the controller.</p>
    <p><strong>Services:</strong> Collection term for all of our products, services and games.</p>
    <p><strong>Cookies:</strong> Cookies are small text files that are stored by your browser on your desktop computer or mobile device.</p>
    <p><strong>Terms of Service/agreement:</strong> The agreement we enter with you for you to use our services.</p>
    <h3>Our Services</h3>
    <p><strong>Games:</strong> Futbolin</p>
    <p><strong>Web services:</strong> Main website (futbolin.com.ar), forum, support</p>
    <p><strong>Social media:</strong> Facebook pages, Twitter pages, Instagram pages, Youtube channels</p>
    <h3>What personal data do we collect?</h3>
    <p>We always seek to collect the least personal data needed to provide you with the best possible experience when using our services. Most of the personal data we collect and use is required for us to provide our services (regulated in the Terms of Service).</p>
    <h4><strong>Personal data collected when using our games</strong></h4>
    <p>Information we collect, or you provide to us, when you are using our games.</p>
    <p>When you download our games</p>
    <p>When you download our games but don’t log in, some personal data is still stored locally on your device. The personal data is stored for you to keep your progress in the game while using it. If you uninstall the game without logging in, all your progress will be deleted.</p>
    <p><strong>Device and model:</strong> We collect and use this information to adjust for example screen size when you use our services.</p>
    <p>When you log in and create an account</p>
    <p><strong>App specific ID/Game center ID/Google Play ID/Twitter ID/Game Circle ID:</strong> We collect and use this information for you to be able to log in via social media.</p>
    <p><strong>Game Center Alias/Google Play Alias/Game Circle Alias:</strong> We collect and use this information for support issues, in case you have forgotten which account you are logged in with.</p>
    <p><strong>Twitter Handle:</strong> We collect and use this information for support issues, in case you have forgotten which account you are logged in with.</p>
    <p><strong>Email address:</strong> When you register we require your email address to be used as your unique identifier to login. This information is not visible to other users.</p>
    <p><strong>Full name:</strong> We collect this information to show to other users instead of your email address.</p>
    <p>When visiting our website</p>
    <p>Our main website, futbolin.com.ar, uses cookies to keep information related to the current session and no personal information is saved in them.</p>
    <h3>What do we use your personal data for?</h3>
    <p>Our main purpose of processing your personal data is to provide you with our games and other services to fulfill our agreement in Terms of Service.</p>
    <h4><strong>We use your personal data for the following purposes in accordance with applicable laws:</strong></h4>
    <p>To provide, operate, improve and maintain all our services and your account(s) ; personalize all content of our services; send technical notices, updates and security alerts; support and troubleshooting reasons; send support and administrative messages; provide news and information about our services; monitor the activities of users playing our games and using our services; facilitate sharing on social networks; provide adults with advertising in accordance with given consent and/or applicable laws; identify, fix, and troubleshoot bugs and service errors, provide software updates etc; resolve disputes, investigate and help to prevent fraud and illegal behavior, comply with the law, and to enforce our agreements and policies; survey users opinions about our services and related matters through surveys, social media channels or questionnaires; communication reasons related to our services; manage our services and send you confirmations and important information about your account, products, purchases, subscriptions, and warranties; present offers and/or information relating to our services and other games that you might like; make recommendations to you; personalize advertising for you and deliver targeted marketing, service updates and promotional offers.</p>
    <h3>What legal basis do we have for processing your personal data?</h3>
    <h4><strong>Agreement</strong></h4>
    <p>We collect and process your personal data in order to fulfill the agreement (Terms of Service) that is necessary for you to use our services.</p>
    <h4><strong>Concent</strong></h4>
    <p>We ask for your consent to accept our use of cookies, and you can withdraw your consent to cookies by updating the settings in your browser any time.</p>
    <h4><strong>Complying with legal obligations</strong></h4>
    <p>We will process your personal data when we have a legal obligation to do so.</p>
    <h3>For how long do we store your personal data?</h3>
    <p>We do not keep your personal data for longer than is necessary for the purposes of performing the agreement unless further storage is required in order to establish, exercise or defend a legal claim or to comply with applicable law, including accounting rules.</p>
    <h3>Who do we share your personal data with?</h3>
    <p>We share your personal data with our affiliates and other trusted businesses or persons to process it for us, based on our instructions and in compliance with our Privacy Policy.</p>
    <p>We may share your personal data with our affiliates, third-party agents and contractors in order to provide our services to you, for ongoing development, for analytical purposes etc. We will only provide personal data to such third party agents and contractors for their performances of their specific assignments for us and consistent with this Privacy Policy, and for no other purposes and provided that such third-party agents and contractors have ensured an adequate level of data protection in accordance with all applicable data protection legislation and/or through agreements with us.</p>
    <h4><strong>Social networks</strong></h4>
    <p>Where our services are accessed and/or provided through social networks.</p>
    <h3>Payment information</h3>
    <p>In order to buy items from our merchandise shop you are required to pay using in-game credits (Fúlbos). When purchasing such in-game credits you may be asked by the platform/service providers to provide certain personally identifiable information, such as full name, billing address, email address, phone number and credit card number/expiration date etc. Please note that you must be the age of 18 or older to make purchases in our games or other services.</p>
    <p>Once you have successfully entered valid credit card information and completed the order process, a purchasing account will be created and maintained for them. The platform/service providers will use the information provided to process your order and to send order confirmations via email, as well as to make future purchases easier for you. We do not sell, transfer or share customer information with third parties, except where applicable the information is transferred, disclosed and shared with our third-party agent(s) who uses the information solely to handle and deliver certain online activities necessary to operate our business (e.g. processing orders and payments).</p>
    <h3>Security</h3>
    <p>We have taken reasonable steps to ensure that the personal data we collect is secure and we have taken reasonable measures to protect the confidentiality, security, and integrity of the personal data collected from our users. Personal data is stored in secure operating environments that are not available to the public and that are only accessible to authorized employees and contractors. We also have security measures in place to protect the loss, misuse, and alteration of the personal data under our control. However, there is no such thing as perfect security. As a result, although we strive to protect personal data, we cannot ensure or warrant the security of any personal data transmitted to us through or in connection with our services, that we store on our systems or that is stored on our service providers systems.</p>
    <p>Please note that we may provide links to other games and websites that are operated and hosted by third parties who may have their own personal data collection practices. Those other games and websites are governed by their own privacy policies, which may be substantially different from our policy. Visitors to other games and websites are encouraged to review the privacy policies and personal data collection practices of those websites.</p>
    <h3>Your rights</h3>
    <p>You have the following rights regarding your personal data:</p>
    <h4><strong>The right to request access</strong></h4>
    <p>You may request access to your personal data. This includes confirmation as to whether or not personal data concerning you are being processed, and, where that is the case, access to the personal data and the following:</p>
    <p>The purposes of the processing; the categories of personal data concerned; the recipients or categories of recipient to whom the personal data have been or will be disclosed, in particular recipients in third countries or international organizations; where possible, the intended period for which the personal data will be stored or, if not possible, the criteria used to determine that period; the existence of the right to request from the controller rectification or erasure of personal data or restriction of processing of personal data concerning you or to object to such processing; the right to lodge a complaint with a supervisory authority; where the personal data are not collected from you, any available personal data as to the source; the existence of automated decision-making, including profiling and, at least in those cases, meaningful information about the logic involved, as well as the significance and the envisaged consequences of such processing affecting you.</p>
    <p>When personal data are transferred to a third country or to an international organization, you have the right to be informed of the appropriate safeguards relating to the transfer.</p>
    <p>You shall be provided a copy of the personal data undergoing processing. For any further copies requested, we may charge a reasonable fee based on administrative costs. When you make the request by electronic means, and unless otherwise requested by you, the information shall be provided in a commonly used electronic form. The right to obtain a copy shall not adversely affect the rights and freedoms of others. Please note that the access may be restricted due to intellectual property or trade secrets.</p>
    <h4><strong>The right of correction</strong></h4>
    <p>You have the right to have inaccurate personal data rectified.</p>
    <h4><strong>The right of erasure</strong></h4>
    <p>You have the right to have your personal data erased where one of the following grounds applies:</p>
    <p>The Personal data is no longer necessary in relation to the purposes for which it was collected or otherwise processed, if you have withdrawn your consent and there are no other legal grounds for the processing, if you have objected to the processing and there are no overriding legitimate grounds for the processing, the personal data have to be erased for compliance with a legal obligation in Union or Member State law, the personal data have been unlawfully processed or the personal data have been collected in relation to the offer of information society services.</p>
    <p>Please note that your right to erasure may be limited if the data are necessary for compliance with a legal obligation or for the establishment, exercise or defense of legal claims. If you exercise this right, you will not be able to use our services and note that we can not recreate erased data.</p>
    <h4><strong>The right to restriction</strong></h4>
    <p>You have the right to obtain restriction of processing in certain circumstances. If you have the right to restriction, we will only process your personal data with your consent or for the establishment, exercise or defense of a legal claim or to protect a person or important grounds of public interest.</p>
    <h4><strong>The right to data portability</strong></h4>
    <p>You have the right to receive your personal data that you have provided to us in a structured, commonly used and machine-readable format and have the right to transmit that data to another controller, when possible. However, we do not have the technical capability for any direct transmission of your personal data.</p>
    <h4><strong>The right to object</strong></h4>
    <p>You have the right to object to the personal data processing on grounds relating to your particular situation when the data are processed based on the balancing of interest rule. In this case, we will cease the processing unless there are compelling legitimate grounds for the processing which override your interests, rights and freedoms or if the processing is necessary for the establishment, exercise or defense of legal claims. You have the right to object to our processing of your personal data for direct marketing purposes at any time. We will cease the processing of your personal data for this purpose after the objection. Please note that if you exercise this right, your user license to use our services may cease automatically (stated in Terms of Service).</p>
    <h4><strong>The right to withdraw consent</strong></h4>
    <p>If we have asked for your consent to our processing of your personal data, you have the right to withdraw your consent at any time. If you withdraw your consent, we will cease processing of the personal data for which you have withdrawn consent, unless we have a legal obligation for processing your data. Please note that if you withdraw your consent to any processing required in Terms of Service (i.e. terminate the agreement), your licence for using our services will cease automatically. The withdrawal of your consent does not affect the lawfulness of processing based on your consent before its withdrawal.</p>
    <h4><strong>Changing or deleting account information</strong></h4>
    <p>You can access, change and delete some of the personal data through you profile(s). Information will be updated as soon as possible. Deleted information may persist in backup copies for a reasonable period of time but will not be generally available to other users or visitors of the services. You cannot however remove communications made in any communication features, which might have been shared with other users (for example sending personal messages to another users).</p>
    <h4><strong>When you want to invoke any rights</strong></h4>
    <p>If you wish to invoke any of the rights described above, you may contact us at any time. We will process and answer your requests without undue delay and in any event within one month of our receipt of the request unless a longer period is required due to the complexity of the request. In this case, our response time can be up to three months.</p>
    <h3>Disputes</h3>
    <h4><strong>Disputes between you and Futbolin</strong></h4>
    <p>Our goal is to resolve disputes fairly and quickly. For all disputes against Futbolin, you agree to first contact us and try to resolve the dispute informally by sending a written notice of the claim (“notice”) to us. The notice must be sent via registered letter. The notice must (a) include your name, your residential address and email address and/or mobile phone number associated with your account registered with us and/or the platform/service provider; (b) describe the type and reason for the claim; and (c) specify specific compensation sought, if any. If we cannot agree on a solution to the dispute within 60 days of receiving such a notice, either party may initiate legal proceedings.</p>
    <h4><strong>User disputes</strong></h4>
    <p>You are solely responsible for your interactions with other users of our services. We reserve the right, but have no obligation, to monitor disputes between you and other users.</p>
    <h3>Arbitration</h3>
    <p>If you are located within the United States of America, the following applies to you: Any claim (excluding claims for injunctive or other equitable relief) where the total amount of the award sought by either party is less than $10,000 shall be resolved via binding non-appearance-based arbitration initiated through the American Arbitration Association (“AAA”). The AAA Rules are available online at www.adr.org or by calling the AAA at 1-800-778-7879. In any such arbitration, the parties and AAA must comply with the following rules: (a) the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; (b) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; (c) the arbitrator may award injunctive or declaratory relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim; and (d) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Nothing in this Agreement shall prevent either party from seeking remedies in small claims court of competent jurisdiction.</p>
    <p>The right to refrain from arbitration. You may choose to waive this arbitration term. Then neither you nor Futbolin can demand that the other party take part in arbitration proceedings. In order to refrain, you must inform Futbolin in writing about this within 30 days of obtaining notice of this Arbitration section. You must provide the name and address, the email address associated with your account associated with the service (if you have one) and a clear wording that you want to waive the arbitration terms. If you do not waive this arbitration section it will continue to apply to you.</p>
    <h3>Class action waiver</h3>
    <p>You agree that any and all claims must be made in your individual capacity, and not as a plaintiff or class member in any purported class or representative proceeding.</p>
    <h3>Claims</h3>
    <p>You and Futbolin agree that any case of action arising out of or related to the Terms of Service or this Privacy Policy must commence within one (1) year after the cause of action accrues. Otherwise, such cause of action is permanently barred.</p>
    <h3>Changes to our Privacy Policy</h3>
    <p>This Privacy Policy applies to all information collected by us or provided to us on and after the Effective Date. This Privacy Policy is subject to change and we may make any changes to this Privacy Policy as we see fit. Futbolin will notify you of material changes by posting them in our games, or on the websites etc. You are encouraged to check back and review this Privacy Policy from time to time so that you will always know what information is collected, how it is used, and to whom it is disclosed. Your continued use of our services subject to this Privacy Policy will signify your acceptance of Privacy Policy changes.</p>
    <p>Last Updated: July 1, 2019</p>
@endsection